# log level
logging.level: 
  root: WARN
  org.springframework: DEBUG
  org.apache.coyote.http11.Http11InputBuffer: DEBUG
  com.edu.ahtcm.xg.fos: DEBUG
  sample.mybatis.mapper: DEBUG
  org.apache.ibatis: DEBUG